# Hacking with Pandas

## Masks (boolean array) vs query

Filter the year 2021

In [1]:
import pandas as pd

df_energy = pd.read_csv('all-technology_2019-2021.csv', index_col=0)
df_energy

              technology  year  month  day  hour  generation_mwh
0                 Carbon  2019      1    1     0          1867.0
1                 Carbon  2019      1    1     1          1618.0
...                  ...   ...    ...  ...   ...             ...
420862  Other Renewables  2021     12   31    22           607.5
420863  Other Renewables  2021     12   31    23           591.6

[420864 rows x 6 columns]

### Dummy solution

### Proficient solution

## Query with multiple conditions

Filter the year `2021` and `Eolic` technology:

In [2]:
df_energy

              technology  year  month  day  hour  generation_mwh
0                 Carbon  2019      1    1     0          1867.0
1                 Carbon  2019      1    1     1          1618.0
...                  ...   ...    ...  ...   ...             ...
420862  Other Renewables  2021     12   31    22           607.5
420863  Other Renewables  2021     12   31    23           591.6

[420864 rows x 6 columns]

### Dummy solution

### Proficient solution

## Filter rows with regular expressions

Filter all `fiat` from the following `DataFrame`:

In [71]:
import seaborn as sns

df_mpg = sns.load_dataset('mpg')
df_mpg

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
...,...,...,...,...,...,...,...,...,...
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10

### Dummy solution

In [72]:
list_fiat = ['fiat 124b', 'fiat 124 sport coupe', 'fiat 128', 'fiat 128', 'fiat 124 tc', 'fiat x1.9', 'fiat 131', 'fiat strada custom']

mask_fiat = df_mpg.name.isin(list_fiat)
dff = df_mpg[mask_fiat]
dff

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
52,30.0,4,88.0,76.0,2065,14.5,71,europe,fiat 124b
114,26.0,4,98.0,90.0,2265,15.5,73,europe,fiat 124 sport coupe
117,29.0,4,68.0,49.0,1867,19.5,73,europe,fiat 128
147,24.0,4,90.0,75.0,2108,15.5,74,europe,fiat 128
148,26.0,4,116.0,75.0,2246,14.0,74,europe,fiat 124 tc
151,31.0,4,79.0,67.0,2000,16.0,74,europe,fiat x1.9
182,28.0,4,107.0,86.0,2464,15.5,76,europe,fiat 131
304,37.3,4,91.0,69.0,2130,14.7,79,europe,fiat strada custom

### Proficient solution

## Regex flag to IGNORECASE

Select all `sport` cars from the `name`:

In [74]:
df_mpg['name'] = df_mpg['name'].str.title()
df_mpg

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,Chevrolet Chevelle Malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,Buick Skylark 320
...,...,...,...,...,...,...,...,...,...
396,28.0,4,120.0,79.0,2625,18.6,82,usa,Ford Ranger
397,31.0,4,119.0,82.0,2720,19.4,82,usa,Chevy S-10

### Dummy solution

### Proficient solution

## Filter axis with Regular Expressions

Select all `fiat` from the following `DataFrame`:

In [66]:
df_mpg = df_mpg.set_index('name')
df_mpg

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
name,,,,,,,,
chevrolet chevelle malibu,18.0,8,307.0,130.0,3504,12.0,70,usa
buick skylark 320,15.0,8,350.0,165.0,3693,11.5,70,usa
...,...,...,...,...,...,...,...,...
ford ranger,28.0,4,120.0,79.0,2625,18.6,82,usa
chevy s-10,31.0,4,119.0,82.0,2720,19.4,82,usa

### Dummy solution

### Proficient solution

## The DataFrame order matters

Visualize the following `DataFrame` with the bars in decreasing order:

In [91]:
dff = (df_energy
    .query('year == 2021')
    .groupby('technology').generation_mwh.sum()
    .reset_index()
)
dff

       technology  generation_mwh
0          Carbon       5016801.7
1    Cogeneration      26373562.5
..            ...             ...
14  Total Exports     -20155317.7
15  Total Imports      21604101.0

[16 rows x 2 columns]

### Dummy solution

### Proficient solution

Also, you may reverse the visualization order `Ascending=False`

## Pivot tables vs groupby

Summarise the `generation_mwh` by `technology` and `month`.

In [111]:
dff = df_energy.query('year == 2021')
dff

              technology  year  month  day  hour  generation_mwh
17544             Carbon  2021      1    1     0           250.0
17545             Carbon  2021      1    1     1           250.0
...                  ...   ...    ...  ...   ...             ...
420862  Other Renewables  2021     12   31    22           607.5
420863  Other Renewables  2021     12   31    23           591.6

[140160 rows x 6 columns]

### Dummy solution

### Proficient solution

## Highlight the significant values with `background_gradient()`

### Dummy solution

In [114]:
dff = dff.pivot_table(index='technology', columns='month', values='generation_mwh', aggfunc='sum')
dff

month,1,2,3,4,5,6,7,8,9,10,11,12
technology,,,,,,,,,,,,
Carbon,569862.6,186166.0,250334.3,275498.8,338188.1,433752.1,311105.2,327367.5,484822.4,534670.4,580637.8,724396.5
Cogeneration,2404774.2,1852452.1,2258929.9,2212108.8,2235879.1,2222424.2,2305126.9,2149075.0,2191493.1,2160983.6,2184241.9,2196073.7
...,...,...,...,...,...,...,...,...,...,...,...,...
Total Exports,-1767893.4,-1713308.0,-1560906.7,-1593086.7,-1766213.8,-1145451.6,-1409599.7,-1550998.8,-1301197.9,-1531946.1,-2319110.6,-2495604.4
Total Imports,2019413.2,1555339.1,1797468.1,1886314.9,2061748.8,2217776.5,2145289.0,2317818.8,1854517.1,1573061.6,995160.5,1180193.4

### Proficient solution

Colour the following `DataFrame` based on the column values using `.style` property.

## Format the values to shorten decimals

### Dummy solution

In [ ]:
dff.style.background_gradient()

### Proficient solution

## From absolute to the thousands

Don't show all digits of the thousands. For example: 20 000 should be 20.

### Dummy solution

In [ ]:
(dff
 .style
    .background_gradient()
    .format(precision=2)
)

### Proficient solution

## Specify the darkest value

### Dummy solution

In [120]:
dff = dff.div(1000)

(dff
 .style
    .background_gradient()
    .format(precision=2)
)

### Proficient solution

## Change the color palette to the topic theme

### Dummy solution

In [123]:
(dff
 .style
    .background_gradient(vmin=dff.values.min(), vmax=dff.values.max())
    .format(precision=2)
)

### Proficient solution